---
- name: Create FlexGet virtualenv
  shell: su -c '{{ venv_bin }} lib/flexget' rtorrent
  args:
    executable: /bin/bash
    chdir: /home/rtorrent
    creates: /home/rtorrent/lib/flexget/bin/pip

- name: Install FlexGet
  shell: su -c 'lib/flexget/bin/pip install flexget' rtorrent
  args:
    executable: /bin/bash
    chdir: /home/rtorrent
    creates: /home/rtorrent/lib/flexget/bin/flexget

- name: Create flexget ~/bin symlink
  file: src=../lib/flexget/bin/flexget path=/home/rtorrent/bin/flexget state=link owner=rtorrent group=rtorrent

- name: Create default FlexGet config (so --help works)
  copy: content="" dest=/home/rtorrent/lib/flexget/config.yml owner=rtorrent group=rtorrent mode=0640 force=no
