---
- name: Install tools + build dependencies for PyroScope
  apt: name={{ item }} state=latest
  with_items:
    - git
    - subversion
    - build-essential
    - python-setuptools
    - python-pkg-resources
    - python-virtualenv
    - python-dev
    - python-pip
    - libreadline-dev
    - libsqlite3-dev
    - libxml2-dev
    - libxslt1-dev

- name: Install FFI
  apt: name={{ item }} state=latest
  when: not(ansible_distribution == "Debian") or not(ansible_distribution_major_version == "7")
  with_items:
    - python-cffi
    - libffi-dev

- name: git clone 'pyrocore'
  shell: su -c 'git clone https://github.com/pyroscope/pyrocore.git pyroscope' rtorrent
  args:
    executable: /bin/bash
    chdir: /home/rtorrent/lib
    creates: /home/rtorrent/lib/pyroscope/.gitignore

- name: Initial 'pyroscope' installation
  shell: su -c './update-to-head.sh ~/.local/pyenv/versions/2.7.10/bin/python' rtorrent
  args:
    executable: /bin/bash
    chdir: /home/rtorrent/lib/pyroscope
    creates: /home/rtorrent/lib/pyroscope/bin/pyroadmin

- name: Installed versions
  name: Get PyroScope & Python version
  shell: "/home/rtorrent/bin/pyroadmin --version ; /home/rtorrent/lib/pyroscope/bin/python --version 2>&1"
  changed_when: False
  register: pyro_versions
- debug: var=pyro_versions.stdout_lines

- name: Copy helper scripts & cron jobs
  copy: src=bin/{{ item }} dest=/home/rtorrent/bin/{{ item }} owner=rtorrent group=rtorrent mode=0750
  with_items:
    - rt-throttle
    - _cron_autolabel

- name: Copy ~/etc config files (once)
  copy: src=etc/{{ item }} dest=/home/rtorrent/etc/{{ item }} owner=rtorrent group=rtorrent mode=0640 force=no
  with_items:
    - autolabel_rules

- name: Add rtorrent cron job '_cron_autolabel'
  cron: user=rtorrent minute=*/31 name=_cron_autolabel job="~/bin/_cron_autolabel --cron"
