---
- name: Install runtime dependencies for rTorrent-PS
  apt: name={{ item }} state=latest
  with_items:
    - tmux
    - locales

- name: Install build tools for rTorrent-PS
  apt: name={{ item }} state=latest
  with_items:
    - git
    - wget
    - build-essential
    - libtool
    - autoconf
    - automake

- name: Install build dependencies for rTorrent-PS
  apt: name={{ item }} state=latest
  with_items:
    - libssl-dev
    - libcppunit-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libsigc++-2.0-dev

- name: Create rtorrent group
  group: name=rtorrent state=present

- name: Create rtorrent user
  user: name=rtorrent comment="rTorrent Client" group=rtorrent groups=users shell=/bin/bash

- name: Create rtorrent home directory
  file: path=/home/rtorrent state=directory owner=rtorrent group=rtorrent mode=0750

- name: Create rtorrent home subdirs
  file: path=/home/rtorrent/{{ item }} state=directory owner=rtorrent group=rtorrent mode=0750
  with_items:
    - bin
    - src
    - tmp
    - .local
    - .local/profile.d

- name: Copy rtorrent dot files
  copy: src=dotfiles/{{ item }} dest=/home/rtorrent/.{{ item }} owner=rtorrent group=rtorrent mode=0640
  with_items:
    - bash_aliases

- name: Create rtorrent /var symlink
  file: src=/home/rtorrent/rtorrent path=/var/torrent state=link

- name: Install initial rtorrent crontab
  copy: src=crontab dest=/var/spool/cron/crontabs/rtorrent owner=rtorrent group=crontab mode=0600 force=no
