---
- name: Install runtime dependencies for rTorrent-PS
  apt: name={{ item }} state=latest
  with_items:
    - tmux
    - locales

- name: Install build tools for rTorrent-PS
  apt: name={{ item }} state=latest
  with_items:
    - git
    - wget
    - build-essential
    - libtool
    - autoconf
    - automake

- name: Install build dependencies for rTorrent-PS
  apt: name={{ item }} state=latest
  with_items:
    - libssl-dev
    - libcppunit-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libsigc++-2.0-dev

- name: Create rtorrent group
  group: name=rtorrent state=present

- name: Create rtorrent user
  user: name=rtorrent comment="rTorrent Client" group=rtorrent groups=users append=yes shell=/bin/bash

- name: Create rtorrent home directory
  file: path=/home/rtorrent state=directory owner=rtorrent group=rtorrent mode=0750

- name: Create rtorrent home subdirs
  file: path=/home/rtorrent/{{ item }} state=directory owner=rtorrent group=rtorrent mode=0750
  with_items:
    - bin
    - etc
    - lib
    - rtorrent
    - rtorrent/.session
    - rtorrent/backups
    - rtorrent/done
    - rtorrent/log
    - rtorrent/watch
    - rtorrent/watch/load
    - rtorrent/watch/start
    - rtorrent/work
    - src
    - tmp
    - .local
    - .local/profile.d

- name: Copy rtorrent dot files
  copy: src=dotfiles/{{ item.name }} dest=/home/rtorrent/.{{ item.name }} owner=rtorrent group=rtorrent mode=0640 force={{ item.force }}
  with_items:
    - { name: bash_aliases, force: yes }
    - { name: tmux.conf, force: no }

- name: Copy rtorrent scripts
  copy: src=bin/{{ item }} dest=/home/rtorrent/bin/{{ item }} owner=rtorrent group=rtorrent mode=0750
  with_items:
    - _event.download.finished

- name: Render rtorrent bash helpers
  template: src=bin/{{ item }} dest=/home/rtorrent/bin/{{ item }} owner=rtorrent group=rtorrent mode=0640
  with_items:
    - _tools.sh

- name: Create rtorrent /var symlink
  file: src=/home/rtorrent/rtorrent path=/var/torrent state=link

- name: Install initial rtorrent crontab
  copy: src=crontab dest=/var/spool/cron/crontabs/rtorrent owner=rtorrent group=crontab mode=0600 force=no

- name: Add rtorrent cron job 'rt_backup_session'
  cron: user=rtorrent minute=7 hour=0 name=rt_backup_session job="cd /var/torrent && tar cfz \"backups/session-$(date +'\%u').tgz\" .session/"

- name: Render default configuration and start script
  template: src="rtorrent/{{ item.name }}" dest="/home/rtorrent/rtorrent/{{ item.name }}" owner=rtorrent group=rtorrent mode="{{ item.mode }}" force="{{ force_cfg }}"
  with_items:
    - { name: 'rtorrent.rc', mode: '0640' }
    - { name: 'start', mode: '0750' }

- name: Render default "Local settings" include file
  template: src=rtorrent/_rtlocal.rc dest=/home/rtorrent/rtorrent/_rtlocal.rc owner=rtorrent group=rtorrent mode=0640 force=no

- name: Create rutorrent include placeholder
  copy: content="" dest=/var/torrent/_rutorrent.rc owner=rtorrent group=rtorrent mode=0640 force=no
