---
- name: Install PHP and plugin packages
  apt:
    state: latest
    name:
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-fpm"
      - "{{ php_apcu }}"
      - sox

- name: Download ruTorrent release archive
  get_url:
    dest: "/root/ruTorrent-{{ rutorrent_version }}.zip"
    url: "https://github.com/Novik/ruTorrent/archive/v{{ rutorrent_version }}.zip"
    validate_certs: no

- name: Unpack ruTorrent release archive
  unarchive:
    copy: no
    src: "/root/ruTorrent-{{ rutorrent_version }}.zip"
    dest: /home/rutorrent
    creates: /home/rutorrent/ruTorrent-master/conf/config.php

- name: Symlink ruTorrent release
  file:
    src: "/home/rutorrent/ruTorrent-{{ rutorrent_version }}"
    path: "/home/rutorrent/ruTorrent-master"
    state: link

- name: Download additional themes
  get_url:
    dest: "/root/InAnimaTe-rutorrent-themes.zip"
    url: "https://github.com/InAnimaTe/rutorrent-themes/archive/master.zip"

- name: Unpack additional themes
  unarchive:
    copy: no
    src: "/root/InAnimaTe-rutorrent-themes.zip"
    dest: /home/rutorrent/src
    creates: /home/rutorrent/src/rutorrent-themes-master/README.md

- name: Symlink additional themes
  file:
    src: "/home/rutorrent/src/rutorrent-themes-master/{{ item }}"
    path: "/home/rutorrent/ruTorrent-master/plugins/theme/themes/{{ item }}"
    state: link
  with_items:
    - Agent46
    - OblivionBlue
