---
- name: Create .local directory
  file: path=/home/rtorrent/.local state=directory owner=rtorrent group=rtorrent mode=0750

- name: Probe pyenv checkout
  stat: path=/home/rtorrent/.local/pyenv/plugins/pyenv-installer/.gitignore
  register: pyenv_flagfile

- name: git clone pyenv project
  git: repo=https://github.com/yyuu/pyenv.git dest=/home/rtorrent/.local/pyenv
  when: not pyenv_flagfile.stat.exists

- name: Create plugins directory
  file: path=/home/rtorrent/.local/pyenv/plugins state=directory owner=rtorrent group=rtorrent mode=0750

- name: git clone pyenv plugins
  git: repo=https://github.com/yyuu/{{ item }}.git dest=/home/rtorrent/.local/pyenv/plugins/{{ item }}
  when: not pyenv_flagfile.stat.exists
  with_items:
    - pyenv-doctor
    - pyenv-update
    - pyenv-virtualenv
    - pyenv-which-ext
    - pyenv-installer

- name: Fix pyenv ownership
  file: path=/home/rtorrent/.local/pyenv state=directory recurse=true owner=rtorrent group=rtorrent
  when: not pyenv_flagfile.stat.exists

- name: Install pyenv activation
  copy: src=pyenv.sh dest=/home/rtorrent/.local/profile.d/pyenv.sh owner=rtorrent group=rtorrent mode=0640

- name: Install Python 2.7.13
  shell: su -c '. .bash_aliases; TMPDIR=$PWD/tmp pyenv install 2.7.13' rtorrent
  args:
    executable: /bin/bash
    chdir: /home/rtorrent
    creates: /home/rtorrent/.local/pyenv/versions/2.7.13/bin/python

- name: Define global pyenv version
  copy: content="2.7.13" dest=/home/rtorrent/.local/pyenv/version owner=rtorrent group=rtorrent mode=0640 force=no

- name: Install virtualenv and update pip
  shell: su -c '.local/pyenv/versions/2.7.13/bin/pip install -U pip virtualenv' rtorrent
  args:
    executable: /bin/bash
    chdir: /home/rtorrent
    creates: /home/rtorrent/.local/pyenv/versions/2.7.13/bin/virtualenv
