---
- name: Install basic tools
  apt: name={{ item }} state=latest
  with_items:
    - bind9-host
    - curl
    - htop
    - httpie
    - links
    - lsof
    - ncdu
    - tmux
    - unzip
    - wget
