---
- name: Restart php-fpm
  service: name=php{{ php_version }}-fpm state=restarted

- name: Test and restart nginx
  command: nginx -t
  notify: Restart nginx

- name: Restart nginx
  service: name=nginx state=restarted

- name: Test and reload nginx
  command: nginx -t
  notify: Reload nginx

- name: Reload nginx
  service: name=nginx state=reloaded
